### PR TITLE
Make py3 compliant

### PR DESCRIPTION
**Pull request by Algomorph**
This will allow users to build cpp2py for python 3.X. Based on tayral/cpp2py py3 branch.
Seems like it still works for python 2.X (tested).

### CODE REVIEW

**Comment by Wentzell** [comment]
Hey @Algomorph, @tayral,

Thank you for the changes! I have gathered them on the ```DEV_PY3``` branch of cpp2py
with a set of corrections that were necessary for ```TRIQS/unstable``` to compile again.
Still the version is not fully backward compatible and the TRIQS library shows test failures in
almost all Python tests.

```
The following tests FAILED:
        198 - operators_py (Failed)
        199 - atom_diag_python (Failed)
        202 - gf_imfreq (Failed)
        203 - gf_block (Failed)
        204 - gf_init (Failed)
        205 - gf_density (Failed)
        206 - gf_base_op (Failed)
        207 - gf_fourier (Failed)
        208 - gf_slicing (Failed)
        209 - g_tau_mul_py (Failed)
        211 - pade (Failed)
        212 - gf_inplace_112 (Failed)
        213 - gf_transpose (Failed)
        214 - hdf5_meshBZ (Failed)
        215 - issue460 (Failed)
        216 - issue437 (Failed)
        219 - tail_issues (Failed)
        220 - gf_eval (Failed)
        222 - block_matrix (Failed)
        223 - gf_tensor_valued (Failed)
        224 - histograms (Failed)
        227 - multivar (Failed)
        228 - g_init_tensor (Failed)
        229 - g_k_om (Failed)
        230 - block2 (Failed)
        231 - bracket (Failed)
        232 - wrap_a (Failed)
        234 - wrap_g (Failed)
        235 - wrap_multivar (Failed)
        236 - blockgf (Failed)
```
Most of the test failures read as follows
```
TypeError: Error: no suitable C++ overload found in implementation of method MeshImFreq.__init__                      
                                                                                                                      
(no C++ name)(double beta, statistic_enum S, int n_max) ->                                                            
 failed with the error :                                                                                              
  Convertion of C++ enum statistic_enum : the object is not a string 
```
This needs to be fixed before we can merge this.

**Comment by Algomorph** [comment]
@Wentzell thank you, I confirm that the branch has major issues. I've already started debugging/weeding some of them out, at least for python 3 case (Python 2 end-of-life is nigh,[ 9 months from now](https://pythonclock.org/)). I will possibly turn to you / other TRIQS maintainers for questions on testing.

Aside: my personal interest in this project is to learn how clang/python can be used a static analysis tool for C++ and potentially to auto-generate Python bindings. The GNU license might be a bit of a setback for me to use cpp2py directly in the future.

**Comment by Wentzell** [comment]
@Algomorph Thank you for looking into the problems. Feel free to update the pull-request
with any fixes or open a new one on the DEV_PY3 branch. 
We are also aware that the Python2 life-cycle is nearing its end and will start the move to Python3 in the near future.

When it comes to the License for cpp2py itself, we already considered changing it to Apache 2.0.
Would this help your cause?

**Comment by Algomorph** [comment]
@Wentzell, thanks for getting back to me. The Apache 2.0 license would definitely help my case 100%.

**Comment by Algomorph** [comment]
@Wentzell , would it be alright if I reformat some of your python files to be [PEP 8](https://www.python.org/dev/peps/pep-0008/)-compliant along the way?

**Comment by Algomorph** [comment]
Also, @Wentzell , I finally got the basic example you have in the README to build for python 3 and work in the python 3 shell.

Problems arise, however, unless I comment out line 360, 'self.add_method(...' or protect it with "if hdf5".
https://github.com/Algomorph/cpp2py/blob/16c4f73d786bd3c0b0a22153d0b61caca94a9b7b/cpp2py/wrap_generator.py#L361

If I don't do this, inevitably I get a bunch of compile-time errors.

Portion of the relevant generated code section in mymodule_wrap.cxx:
```C++

//--------------------- define all functions/methods with args, kwds, including constructors -----------------------------


 static PyObject* Myclass___write_hdf5__(PyObject *self, PyObject *args, PyObject *keywds) {

  static constexpr int n_overloads = 1;

  [[maybe_unused]] PyObject * py_result; //final result, except for constructor

  std::array<pyref,n_overloads> errors;

  // If no overload, we avoid the err_list and let the error go through (to save some code).
    {// overload __write_hdf5__(triqs::h5::group gr, std::string key) -> void
     // define the variable to be filled by the parsing method
     // wrapped types are converted to a pointer, other converted types to a value or a view
     using _type_0 = std::conditional_t<is_wrapped_v<triqs::h5::group>, triqs::h5::group *, triqs::h5::group>;
     _type_0 __gr = _type_0{}; // not default for wrapped type please
```
The errors seem to stem from the `triqs` namespace not being defined on my platform.
```
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx: In function ‘PyObject* Myclass___write_hdf5__(PyObject*, PyObject*, PyObject*)’:
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:278:54: error: ‘triqs’ was not declared in this scope
      using _type_0 = std::conditional_t<is_wrapped_v<triqs::h5::group>, triqs::h5::group *, triqs::h5::group>;
                                                      ^~~~~
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:278:41: error: parse error in template argument list
      using _type_0 = std::conditional_t<is_wrapped_v<triqs::h5::group>, triqs::h5::group *, triqs::h5::group>;
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:278:41: error: template argument 1 is invalid
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:278:41: error: template argument 1 is invalid
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:278:109: error: wrong number of template arguments (2, should be 3)
      using _type_0 = std::conditional_t<is_wrapped_v<triqs::h5::group>, triqs::h5::group *, triqs::h5::group>;
                                                                                                             ^
In file included from /usr/include/c++/8/bits/move.h:55,
                 from /usr/include/c++/8/bits/stl_pair.h:59,
                 from /usr/include/c++/8/utility:70,
                 from /usr/include/c++/8/array:38,
                 from /home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:1:
/usr/include/c++/8/type_traits:2335:79: note: provided for ‘template<bool _Cond, class _Iftrue, class _Iffalse> using conditional_t = typename std::conditional::type’
     using conditional_t = typename conditional<_Cond, _Iftrue, _Iffalse>::type;
                                                                               ^
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:279:6: error: ‘_type_0’ was not declared in this scope
      _type_0 __gr = _type_0{}; // not default for wrapped type please
      ^~~~~~~
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:279:6: note: suggested alternative: ‘wctype_l’
      _type_0 __gr = _type_0{}; // not default for wrapped type please
      ^~~~~~~
      wctype_l
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:285:10: error: parse error in template argument list
         ,converter_for_parser<triqs::h5::group> ,&__gr,converter_for_parser<std::string> ,&__key))
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:285:51: error: ‘__gr’ was not declared in this scope
         ,converter_for_parser<triqs::h5::group> ,&__gr,converter_for_parser<std::string> ,&__key))
                                                   ^~~~
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:285:51: note: suggested alternative: ‘__erf’
         ,converter_for_parser<triqs::h5::group> ,&__gr,converter_for_parser<std::string> ,&__key))
                                                   ^~~~
                                                   __erf
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:289:52: error: template argument 1 is invalid
        static_assert(std::is_reference<decltype(gr)>::value || std::is_pointer<decltype(gr)>::value, "internal error");
                                                    ^
/home/algomorph/Workbench/TestCpp2PyProject/build/mymodule_wrap.cxx:289:92: error: template argument 1 is invalid
        static_assert(std::is_reference<decltype(gr)>::value || std::is_pointer<decltype(gr)>::value, "internal error");

```

Is this by design? Do we want to change this so it works w/o the triqs namespace?

Thanks!

**Comment by Wentzell** [comment]
Hey @Algomorph,

First of all thank you for you continued effort on the Python3 compatibility.

> @Wentzell , would it be alright if I reformat some of your python files to be [PEP 8](https://www.python.org/dev/peps/pep-0008/)-compliant along the way?

This is fine with us. Just out of curiosity which tool are you actually using for the formatting?
If possible, please keep formatting changes in commits separate from other changes. 

> Problems arise, however, unless I comment out line 360, 'self.add_method(...' or protect it with "if hdf5".
> https://github.com/Algomorph/cpp2py/blob/16c4f73d786bd3c0b0a22153d0b61caca94a9b7b/cpp2py/wrap_generator.py#L361
> 
> If I don't do this, inevitably I get a bunch of compile-time errors.

Ok, this part should not be generated if triqs is not available.
In principle one could protect the function in the generated cxx file with
```c++
#ifdef TRIQS_INCLUDED_H5
...
#endif
```
but this would complicate the wrap_generator unnecessarily just to keep this one improved error message. @parcollet What do you think?
I agree that the easiest workaround is to protect the generatation by an ```if hdf5:``` 

```diff
diff --git a/cpp2py/wrap_generator.py b/cpp2py/wrap_generator.py
index 9e16789..a6917dd 100644
--- a/cpp2py/wrap_generator.py
+++ b/cpp2py/wrap_generator.py
@@ -353,10 +353,11 @@ class class_ :
       self.properties= [] # a list of _property
       self.export = export 
 
-      # Init hdf5
-      # If hdf5 is True, wrap the C++, else set an error message 
-      cp = "h5_write(gr, key, self_c);" if hdf5 else 'PyErr_SetString(PyExc_NotImplementedError, "No hdf5 support for %s"); return NULL;'%self.py_type;
-      self.add_method("void __write_hdf5__(triqs::h5::group gr, std::string key)", calling_pattern = cp, doc = "hdf5 writing")
+      # If hdf5 is True, wrap the C++ write function.
+      # We cannot generate a default implementation with an error message as triqs::h5::group might not be available.
+      # FIXME Remove triqs dependence
+      if hdf5:
+          self.add_method("void __write_hdf5__(triqs::h5::group gr, std::string key)", calling_pattern = "h5_write(gr, key, self_c);", doc = "hdf5 writing")
     
       # Init arithmetic
       # expect a tuple : "algebra", "scalar1", "scalar2", etc...
```

**Comment by parcollet** [comment]
I agree. This is, I think, the last TRIQS specific thing to remove, after we took cpp2py out of TRIQS.

**Comment by Wentzell** [comment]
I have now pushed the above patch to master, see 869c2ef.

**Comment by Algomorph** [comment]
Thank you both for your support and prompt feedback. As soon as I have time, I'll continue as follows: 
- I'll explore what the current framework for testing is and ensure that the code works locally for both python2 and python3. I will subsequently squash all commits in this PR for python3 compatibility into one.
- (Optionally) I'll reformat some files using PyCharm as a separate commit.

**Comment by Wentzell** [comment]
> * I'll rebase my current **py3** branch on your master branch, then I'll explore what the current framework for testing is and ensure that the code works locally for both python2 and python3. I will subsequently squash all commits in this PR for python3 compatibility into one.
> * (Optionally) I'll reformat some files using PyCharm as a separate commit.

This sounds like a good plan. You do not have to squash everything into one commit if you think
it makes sense to group the changes into multiple commits.
It would just be good to clean the branch history once before merging.

Also we just changed the license to Apache 2.0, cf. 4e25c3e6224dda23e0e680c7eda767255f5c1330

**Comment by Algomorph** [comment]
Just letting everyone know: I haven't forgotten about this, it's still on my docket, just somewhat swamped at present.

**Comment by Wentzell** [comment]
> Just letting everyone know: I haven't forgotten about this, it's still on my docket, just somewhat swamped at present.

Thanks for letting us now! We hope the current conflicts with master are mostly trivially solvable?

**Comment by Algomorph** [comment]
Hi, all, just finished my BIG THING yesterday. Will be moving on this again now. Yes, conflicts seemed like they were trivial so far.

**Comment by Algomorph** [comment]
> The following tests FAILED:
>         198 - operators_py (Failed)
>         199 - atom_diag_python (Failed)
>         202 - gf_imfreq (Failed)
>         203 - gf_block (Failed)
>         204 - gf_init (Failed)
>         205 - gf_density (Failed)
>         206 - gf_base_op (Failed)
>         207 - gf_fourier (Failed)
>         208 - gf_slicing (Failed)
>         209 - g_tau_mul_py (Failed)
>         211 - pade (Failed)
>         212 - gf_inplace_112 (Failed)
>         213 - gf_transpose (Failed)
>         214 - hdf5_meshBZ (Failed)
>         215 - issue460 (Failed)
>         216 - issue437 (Failed)
>         219 - tail_issues (Failed)
>         220 - gf_eval (Failed)
>         222 - block_matrix (Failed)
>         223 - gf_tensor_valued (Failed)
>         224 - histograms (Failed)
>         227 - multivar (Failed)
>         228 - g_init_tensor (Failed)
>         229 - g_k_om (Failed)
>         230 - block2 (Failed)
>         231 - bracket (Failed)
>         232 - wrap_a (Failed)
>         234 - wrap_g (Failed)
>         235 - wrap_multivar (Failed)
>         236 - blockgf (Failed)

Can you tell me / point to the docs about how to run these tests?

**Comment by Wentzell** [comment]
Hi @Algomorph,

Which version of triqs are you using?

You can run the failing tests separately with e.g.

```ctest -V -R operators_py```

to get all the relevant information on how they are run and what the failure is.

**Comment by Algomorph** [comment]
@Wentzell , thank you!

I wasn't using Triqs before. I'm guessing https://github.com/TRIQS/triqs is the repo, if so, I'll check out the latest release. I'll keep you in the loop if I run into trouble. Timing is once again tight, since I'm going on a much-needed vacation soon, but I'll see if I can get this done in the next 2 days.

**Comment by Wentzell** [comment]
@Algomorph,

You should use the latest development version of triqs (i.e. unstable branch)
given that you are basing your work on cpp2py/master.

The TRIQS library provides a fixed version of cpp2py (as a git subtree) in the triqs/cpp2py directory.

As a first step you should check that TRIQS compiles and passes all tests as it is.

If you want to then check that the altered version of cpp2py passes all TRIQS test
you should replace the triqs/cpp2py directory by a softlink to your altered cpp2py source directory.

Let me know if you have any trouble.

**Comment by Algomorph** [comment]
I'm trying to revive this again, cause I said I'd do it, but I'm having trouble installing cpp2py. I'm getting:
```
File "/usr/local/lib/python3.6/site-packages/cpp2py/doc.py", line 7, in <module>
    import util
ModuleNotFoundError: No module named 'util'
```

This is after sourcing `/usr/local/share/cpp2pyvars.sh` and running `python3 ../install/bin/c++2py mymodule.hpp`

I'm not aware of python 3 resolving paths any differently than python 2. Any ideas? Perhaps I'm missing something?

**Comment by Wentzell** [comment]
Hi @Algomorph,

Thank you for your continued effort!

> I'm not aware of python 3 resolving paths any differently than python 2. Any ideas? Perhaps I'm missing something?

Its seems that "In python 3 all imports are absolute unless a relative path is given to perform the import from", see [here](https://stackoverflow.com/questions/31269437/how-do-i-import-from-a-file-in-the-current-directory-in-python-3/31269588).

Given that the module structure cpp2py has at most two layers I would suggest to just replace the failing imports with absolute imports, i.e. `import util` -> `import cpp2py.util` and so on.

**Comment by Algomorph** [comment]
@Wentzell thanks, full paths seem to be working.
Considering Python 2 support is ending soon-ish, how should I proceed about potentially re-adding / retaining optional Python 2 support?

**Comment by Algomorph** [comment]
(2) Also, I've checked out TRIQS (the unstable branch), and it looks like it has a folder `cpp2py` (and others) that also belong to the `cpp2py` repository... What am I to do in order to test this? I was working on the original `TRIQS/cpp2py` repo. Should I just replace the folders with cpp2py from my own branch? Why isn't cpp2py a git submodule in TRIQS, let alone tests pertinent to specifically cpp2py being included in that repo?

**Comment by Wentzell** [comment]
Dear @Algomorph,

We refrained from working with submodules as this complicates the experience of our users,
many of which are building the project from source. Instead we have opted to include cpp2py as
a `git subtree` which we update regularly. You should be fine to fully replace the cpp2py folder in TRIQS with either a copy or a softlink.

**Comment by Algomorph** [comment]
@Wentzell if you want to preserve loose coupling/modularity to make maintenance easier while keeping the build-from-source users happy, you can possibly use [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html) to check out the cpp2py repository during the cmake conifiguration step of TRIQS and proceed building as you normally do.

But that's an issue for another time. What of trying to preserve Python 2 support concurrently with Python 3 support? Certain things will have to be done one way or another, I think. For instance the cpp2py python scripts currently hard-code a bash call to "python" which still defaults to Python 2 on many systems to date. I guess this will have to be altered based on the python executable discovered during the CMake build of cpp2py.

**Comment by Wentzell** [comment]
Dear @Algomorph,

We have indeed considered `ExternalProject_Add` as an option and decided against it
as this will prohibit users from installing the triqs release tarball without an internet connection.
This can be a problem on some HPC machines.

Did you manage to pass all of the triqs tests using this branch cpp2py?

> But that's an issue for another time. What of trying to preserve Python 2 support concurrently with Python 3 support? Certain things will have to be done one way or another, I think. For instance the cpp2py python scripts currently hard-code a bash call to "python" which still defaults to Python 2 on many systems to date. I guess this will have to be altered based on the python executable discovered during the CMake build of cpp2py.

I agree that the executables in `bin` should be using the cmake-detected Python interpreter.
I have made the necessary changes in 06a05bf on master.

**Comment by Algomorph** [comment]
@Wentzell , no, I have been too busy lately to address this. Feel free to take matters into your own hands at any point, I believe you should have write access to my py3 branch via the PR. Also, adding changes this way instead of committing to your master branch makes things easier because no additional merge/rebase work needs to be done.

**Comment by Wentzell** [comment]
The master branch of cpp2py is now fully Python3 compatible. Python2 support has been dropped.

**Pull request closed without merging**
